version: '3'
services:
  portfolio:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: portfolio
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.portfolio.rule=(Host(`sanjuant.fr`) || Host(`www.sanjuant.fr`))"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.tcp.routers.portfolio.tls.passthrough=true"
      - "traefik.http.services.portfolio.loadbalancer.server.port=3000"

networks:
  web:
    external:
      name: web
